name: Docker Build Image CI

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v5
    - name: steup node js
      uses: actions/setup-node@v4
      with:
        node-version: 24.15.0
        cache: 'npm'
      run: npm ci
      run: npm run build --if-present
      run: npm test
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile_apponitment
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}      
